version: 0.0
os: linux
files:
  - source: /server.js
    destination: /tmp/dientrinhtemp/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
