version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm i -g mocha
      - npm i -g chai
      - npm test
artifacts:
    files:
    - appspec.yml
    - index.html
    - server.js
    - package.json
    - scripts/*
    - node_modules/*